name: Build & Push Docker

on:
  push:
    branches: [ deploy ]        # اتوماتیک: هر push به شاخه‌ی deploy
  workflow_dispatch:            # دستی: از تب Actions خودت اجرا کن

jobs:
  build:
    # اگر self-hosted داری و می‌خواهی همان اجرا کند:
    # runs-on: self-hosted
    # اگر می‌خواهی روی runner خودِ GitHub اجرا شود:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # لاگین به DockerHub با سکرت‌ها
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # مثلا: elaheahmadi
          password: ${{ secrets.DOCKER_PASSWORD }}   # یا بهتر: DOCKER_TOKEN

      # گیت‌گارد: فقط اگر پیام آخرین کمیت با "version:" شروع شود، push = true
      - name: Decide whether to push
        id: gate
        run: |
          MSG="$(git log -1 --pretty=%B | tr -d '\r')"
          if echo "$MSG" | grep -qi '^version:'; then
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
          fi

      - name: Build & (maybe) Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ steps.gate.outputs.push }}   # true/false
          tags: |
            elaheahmadi/flaskrepo:latest
            elaheahmadi/flaskrepo:${{ github.sha }}
